### PR TITLE
Added api endpoints

### PR DESCRIPTION
**Pull request by Lioncat2002**
Added new user endpoint and get user point, access docs via /docs and to see all the members access the /members endpoint

### CODE REVIEW

**Comment by mayankkumar2** [comment]
remove the __pycache__ folders, and add them to gitignore
@Lioncat2002

**Review by mayankkumar2 — CHANGES_REQUESTED** [review]
Remove the __pycache__ files

**Comment by Lioncat2002** [comment]
whoops removing pycache asap

**Review by mayankkumar2 — CHANGES_REQUESTED** [review]
Move secret key to an env variable

**Review by mayankkumar2 — CHANGES_REQUESTED** [review]
Run a pep8 linter on your code

**Review by mayankkumar2 — APPROVED** [review]

**Pull request merged**
